#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Target for Linux x64 (compatible with most cloud/docker envs)
const target = {
  os: "linux",
  arch: "x64",
  // avx2: false, // Optional: uncomment if targeting older hardware, but standard cloud VMs usually support AVX2
}

// Build Frontend
console.log("Building frontend...")
await $`bun install`.cwd(path.resolve(dir, "../app"))
await $`bun run build`.cwd(path.resolve(dir, "../app"))
console.log("Frontend build complete")

const name = "opencode-linux-x64"

await $`rm -rf dist/${name}`

console.log(`building ${name}`)
await $`mkdir -p dist/${name}/bin`

// Copy Frontend Assets
console.log("Copying frontend assets...")
await $`cp -r ../app/dist dist/${name}/bin/public`

const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
const workerPath = "./src/cli/cmd/tui/worker.ts"

// Linux path convention for Bun
const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [solidPlugin],
  sourcemap: "external",
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    //@ts-ignore (bun types aren't up to date)
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    target: "bun-linux-x64", // Explicitly target bun-linux-x64
    outfile: `dist/${name}/bin/opencode`,
    execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
    windows: {},
  },
  entrypoints: ["./src/index.ts", parserWorker, workerPath],
  define: {
    OPENCODE_VERSION: `'${Script.version}'`,
    OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
    OPENCODE_WORKER_PATH: workerPath,
    OPENCODE_CHANNEL: `'${Script.channel}'`,
    OPENCODE_LIBC: `'glibc'`,
  },
})

await $`rm -rf ./dist/${name}/bin/tui`
await Bun.file(`dist/${name}/package.json`).write(
  JSON.stringify(
    {
      name,
      version: Script.version,
      os: ["linux"],
      cpu: ["x64"],
    },
    null,
    2,
  ),
)

console.log(`Build complete: dist/${name}/bin/opencode`)
